### ISSUE TITLE
Installation failure in python 3.8

### ISSUE THREAD

**Issue by rajeev1982** [guilhermechapiewski/simple-db-migrate#42]
Installation fails in python3.8.

```
$ docker run -it python:3.8 /bin/bash
root@4f07de037284:/# python --version
Python 3.8.2
root@4f07de037284:/# pip install simple-db-migrate
Collecting simple-db-migrate
Downloading simple-db-migrate-3.0.0.tar.gz (42 kB)
|████████████████████████████████| 42 kB 402 kB/s
ERROR: Command errored out with exit status 1:
command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k6peapnk/simple-db-migrate/setup.py'"'"'; file='"'"'/tmp/pip-install-k6peapnk/simple-db-migrate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-k6peapnk/simple-db-migrate/pip-egg-info
cwd: /tmp/pip-install-k6peapnk/simple-db-migrate/
Complete output (21 lines):
/tmp/pip-install-k6peapnk/simple-db-migrate/simple_db_migrate/main.py:136: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if destination_version is not '0' and not (self.db_migrate.check_if_version_exists(destination_version) or self.sgdb.get_version_id_from_version_number(destination_version)):
Traceback (most recent call last):
File "", line 1, in
File "/tmp/pip-install-k6peapnk/simple-db-migrate/setup.py", line 4, in
setup(
File "/usr/local/lib/python3.8/site-packages/setuptools/init.py", line 144, in setup
return distutils.core.setup(**attrs)
File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
dist.run_commands()
File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
self.run_command(cmd)
File "/usr/local/lib/python3.8/distutils/dist.py", line 982, in run_command
log.info("running %s", command)
File "/usr/local/lib/python3.8/distutils/log.py", line 46, in info
self._log(INFO, msg, args)
File "/usr/local/lib/python3.8/distutils/log.py", line 31, in _log
stream.write('%s\n' % msg)
File "/usr/local/lib/python3.8/codecs.py", line 378, in write
self.stream.write(data)
TypeError: write() argument must be str, not bytes
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
root@4f07de037284:/#
```

**Comment by rajeev1982** [comment]
Any update on this as I am not able to figure this one out.

**Comment by rajeev1982** [comment]
Looks like the authors of this library don't care about issues. 

I am gonna have to abandon this library as I am not able to figure out how to resolve this issue.

**Comment by wandenberg** [comment]
Let me see if I can help you @rajeev1982. The issue is only the installation on python3.8 or do you have any other issue with encode also?

**Comment by wandenberg** [comment]
Done. New version released
```bash
root@7214a0ce8707:/# pip install simple-db-migrate
Collecting simple-db-migrate
  Downloading simple-db-migrate-3.0.1.tar.gz (42 kB)
     |████████████████████████████████| 42 kB 1.1 MB/s
Building wheels for collected packages: simple-db-migrate
  Building wheel for simple-db-migrate (setup.py) ... done
  Created wheel for simple-db-migrate: filename=simple_db_migrate-3.0.1-py3-none-any.whl size=57897 sha256=70145a06d6e67aa4884ca1c9721606a91a14cc29fd14c2eb94e2a50d9aece712
  Stored in directory: /root/.cache/pip/wheels/dc/f9/31/8a50257b6042d16e73b4a9d7e2aee983341cab32ed3590a1fa
Successfully built simple-db-migrate
Installing collected packages: simple-db-migrate
Successfully installed simple-db-migrate-3.0.1
```

**Comment by rajeev1982** [comment]
Installation was the only issue. I am able to install it now and use it normally.

Thanks for the help.

**Comment by sh0nk** [comment]
Still the installation error remains in 3.0.1. Could you help to fix this?

```
[EnvCommandError]
Command ['C:\\user\\a-repository\\.venv\\Scripts\\pip.exe', 'install', '--no-deps', 'simple-db-migrate==3.0.1'] errored with the following 
return code 1, and output:
Collecting simple-db-migrate==3.0.1
  Using cached simple-db-migrate-3.0.1.tar.gz (42 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\user\a-repository\.venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-3k09gq_o\\simple-db-migrate\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-3k09gq_o\\simple-db-migrate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-q9guf_lb'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-3k09gq_o\simple-db-migrate\
    Complete output (19 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-3k09gq_o\simple-db-migrate\setup.py", line 20, in <module>
        'db-migrate = simple_db_migrate:run_from_argv',
      File "c:\user\a-repository\.venv\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 982, in run_command
        log.info("running %s", command)
      File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\distutils\log.py", line 46, in info
        self._log(INFO, msg, args)
      File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\distutils\log.py", line 31, in _log
        stream.write('%s\n' % msg)
      File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\codecs.py", line 378, in write
        self.stream.write(data)
    TypeError: write() argument must be str, not bytes
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by wandenberg** [comment]
Hi @sh0nk, I never tried to install it on Windows.
And I do not have one available now to check.
Could you run the command that shows in the log, piece by piece, and isolate the first part the fails?

**Comment by sh0nk** [comment]
Yeah I am also wondering if it's windows specific. The commands didn't help unfortunately. The above command was run with poetry which wraps pip, so this time used pip directly to install, but the same traceback with the following header was got.

**Comment by sh0nk** [comment]
Hi @wandenberg ,
I did look into the Windows environment, and found the CLI ran with `cp1252` encoding. The PR #44 fixed the issue on my local, which referred to this encoding support: https://stackoverflow.com/Questions/4374455/how-to-set-sys-stdout-encoding-in-python-3
Could you take a look?
